[[redirects]]
from = "/u"
to = "/u"
status = 200
force = false
[[redirects]]
from = "/login"
to = "/login"
status = 200
force = false
[[redirects]]
from = "/signup"
to = "/signup"
status = 200
force = false
[[redirects]]
from = "/home"
to = "/home"
status = 200
force = false
[[redirects]]
from = "/create"
to = "/create"
status = 200
force = false
[[redirects]]
from = "/publish"
to = "/publish"
status = 200
force = false
